site_name: Leeds BAG Wiki
site_description: "How-to guides, group resources, and documentation for the Leeds BAG research group."
site_author: "Leeds BAG"
repo_name: leeds-bag/bag_wiki
repo_url: https://github.com/leeds-bag/bag_wiki
edit_uri: edit/main/docs

theme:
  name: readthedocs

nav:
  - Home: index.md
  - How-to guides:
      - Linux Cheat Sheet: linux_cheat_sheet.md
      - Python Quick Start: python_quick_start.md
      - Mamba Set Up: conda_setup.md
      - Regridding with Python: how_to_regrid_xesmf_tutorial.md
      

plugins:
  - search
